"""empty message

Revision ID: 7680dca0d655
Revises:
Create Date: 2021-07-29 19:47:46.401875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7680dca0d655'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('username', sa.String(
                        length=40), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('about', sa.Text(), nullable=True),
                    sa.Column('profile_pix', sa.String(
                        length=1000), nullable=True),
                    sa.Column('account_type', sa.String(
                        length=20), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('restaurants',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('address', sa.String(
                        length=255), nullable=False),
                    sa.Column('restaurant_type', sa.String(
                        length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('restaurant_pix', sa.String(
                        length=1000), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('menu_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creator_id', sa.Integer(), nullable=True),
                    sa.Column('restaurant_id', sa.Integer(), nullable=True),
                    sa.Column('food_name', sa.String(
                        length=255), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('food_pix', sa.String(
                        length=1000), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['restaurant_id'], ['restaurants.id'], ),
                    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('description')
                    )
    op.create_table('ratings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('menu_item_id', sa.Integer(), nullable=True),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('review', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['menu_item_id'], ['menu_items.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('saves',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('menu_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['menu_item_id'], ['menu_items.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saves')
    op.drop_table('ratings')
    op.drop_table('menu_items')
    op.drop_table('restaurants')
    op.drop_table('users')
    # ### end Alembic commands ###
